# Matrices

---

### Definitions

$$
M = \begin{bmatrix}
       a_{11} & \dots & a_{1n}          \\
       \vdots &            & \vdots      \\
       a_{m1}         & \dots & a_{mn}
     \end{bmatrix}
$$

The matrix entries are denoted as
$a_{ij}$ where
*i* is the row index and
*j* is the col index.

$(a_{ij})$ denotes the matrix whose entries are $a_{ij}$. Avoid this notation where it risks causing confusion with perhaps more familiar parenthesis usage (order of operation).

**Square matrix**: *n* x *n*

**Row vector**: 1 x *n*

**Column vector**: *n* x 1

---

### Addition

Defined when both matrices have same dimensions.

($s_{ij}$) = ($a_{ij}$) + ($b_{ij}$) 

where

$s_{ij}$ = $a_{ij}$ + $b_{ij}$ 

### Scalar Multiplication

*c* ($a_{ij}$) = ($c a_{ij}$)

### Matrix Multiplication

Defined for matrices A and B where the number of columns in A equals the number of rows of B.


$$
(p_{ij}) = AB
$$

$$
p_{ij} = \sum_{v}a_{iv}b_{vj}
$$

Provides another way to write a system of equations.

$$
a_{11}x_{1} + \dots + a_{1n}x_{n} = b_{1} \\
\vdots                                    \\
a_{m1}x_{1} + \dots + a_{mn}x_{n} = b_{n}
$$

can be expressed as $AX = B$, 
where A is the matrix of coefficients, 
X and B are columns vectors.

---

### Distributive Law

$$
L(A + B) = LA + LB
$$ 
$$
(A + B)R = AR + BR
$$

### Associative Law

$$
(AB)C = A(BC)
$$

### NOT Commutative 

Occasionally can be, but in general **cannot** assume that $AB = BA$

---

### More Definitions

**zero matrix**: All entries are 0. Denoted as just 0 if no confusion.

**diagonal entries**: $a_{ii}$

**diagonal matrix**: [A square matrix] Only nonzero entries are diagonal entries. 

**identity matrix**: The *n* x *n* diagonal matrix whose diagonal entries all equal 1. Denoted $I_{n}$ 

If A is *m* x *n* matrix then

$$
AI_{n} = A 
$$
$$
I_{m}A = A
$$

**inverse matrix**: Denoted by $A^{-1}$

$$
A^{-1}A = I = AA^{-1}
$$

**invertible**: If an inverse exists

**nilpotent** if $A^{k}$ = 0 for some k > 0

---

### Lemma 1

Let A be a square matrix that has a right inverse, a matrix R such that AR = I
and also a left inverse, a matrix L such that LA = I. Then R = L. So A is invertible and R is its inverse.

##### Proof

$$
R = IR = (LA)R = L(AR) = LI = L
$$

---

### Proposition 1
If $A$ and $B$ are invertible,
Then
- $AB$ is invertible
- $A^{-1}$ is invertible
- $(AB)^{-1} = B^{-1}A^{-1}$ (Generalized below)

If $A_{1}, \dots\, A_{m}$ are invertible,
Then

$$
(A_{1} \cdots\ A_{m})^{-1} = A_{m}^{-1} \cdots A_{1}^{-1}
$$

##### Proof

By definition

$$
(A_{1} \cdots\ A_{m})^{-1}(A_{1} \cdots\ A_{m}) = I = (A_{1} \cdots\ A_{m})(A_{1} \cdots\ A_{m})^{-1}
$$

Consider

$$
(A_{1} \cdots\ A_{m})           (A_{m}^{-1} \cdots\ A_{1}^{-1}) =
$$
$$
(A_{1} \cdots\ A_{m-1})  (A_{m}A_{m}^{-1})        (A_{m-1}^{-1} \cdots\ A_{1}^{-1}) =
$$
$$
(A_{1} \cdots\ A_{m-1})     I   (A_{m-1}^{-1} \cdots\ A_{1}^{-1}) =
$$
$$
(A_{1} \cdots\ A_{m-1})(A_{m-1}^{-1} \cdots\ A_{1}^{-1}) =
$$
$$
\dots = A_{1}A_{1}^{-1} = I
$$

Similar logic shows that 

$$
(A_{m}^{-1} \cdots\ A_{1}^{-1})(A_{1} \cdots\ A_{m}) = I
$$

Thus

$$
(A_{1} \cdots\ A_{m})^{-1} = A_{m}^{-1} \cdots\ A_{1}^{-1}
$$

---

### Determinant 

$ad-bc$ is the determinant of a 2x2 matrix. If the determinant is 0 then the matrix is not invertible

$$
\begin{bmatrix}
      a & b \\
      c & d
\end{bmatrix}^{-1} = 
\frac{1}{ad-bc}
\begin{bmatrix}
      d & -b \\
      -c & a
\end{bmatrix}
$$

***n*-dimensional general linear group**: Set of all invertible nxn matrices.

---

### Lemma 2 
A square matrix that has either a row or column of 0s is not invertible.

##### Proof

Given n x n matrices A and B.

If matrix A has row of 0s then the corresponding row in AB also has all 0s.

So at least one diagonal entry of AB is not one.

So $AB \not= I_{n}$

So A has no right inverse.

If matrix A has a column of 0s then the corresponding column in BA also has all 0s.

So at least one diagonal entry of BA is not one.

So $BA \not= I_{n}$

So A has no left inverse.

Thus, A is not invertible. 

---

### Block Multiplication

Can partition matrices.
Can be useful for proving facts about matrices by induction.

$$
M = 
\begin{bmatrix}
       A | B  \\
       \hline
       C | D
\end{bmatrix};
M' = 
\begin{bmatrix}
       A' | B'  \\
       \hline
       C' | D'
\end{bmatrix}
$$

$$
MM' =
\begin{bmatrix}
       A | B  \\
       \hline
       C | D
\end{bmatrix}
\begin{bmatrix}
       A' | B' \\
       \hline
       C' | D'
\end{bmatrix} =
\begin{bmatrix}
       AA' + BC' | AB' + BD'  \\
       \hline
       CA' + DC' | CB' + DD'
\end{bmatrix}
$$

---

### Matrix Units

Simplest nonzero matrices. 

Denoted **$e_{ij}$** has a 1 at position i, j as its only nonzero entry.
A matrix unit uses lower case letter by convention even though it is indeed a matrix.

The set of matrix units is called **basis** for the space of all m x n matrices because every m x n matrix $A = (a_{ij})$ is a **linear combination** of $e_{ij}$

$$
A = \sum_{i,j}a_{ij}e_{ij}
$$

Concrete example

$$
\begin{bmatrix}
       3 & 2 \\
       1 & 4
\end{bmatrix}=
3\begin{bmatrix}
       1 &  \\
        & 
\end{bmatrix} +
2\begin{bmatrix}
        &  1\\
        & 
\end{bmatrix} +
1\begin{bmatrix}
        &  \\
       1 & 
\end{bmatrix} +
4\begin{bmatrix}
        &  \\
        & 1
\end{bmatrix} =
3e_{11} + 2e_{12} + 1e_{21} + 4e_{22}
$$

Given
- m x n matrix unit $e_{ij}$
- n x p matrix unit $e_{mk}$

$$
j = m
$$
$$
e_{ij}e_{mk} = e_{ik}
$$

$$
j \not= m
$$
$$
e_{ij}e_{mk} = 0
$$

---

### Standard basis

The column vector $e_{i}$ has single nonzero entry of 1 at i.

**standard basis of $\mathbb{R}^{n}$** The set $\{e_{1}, \dots, e_{n}\}$

---

### Row Reduction

$AX = Y$ can be computed by operating on the rows of $X$.

$Y_{i} = \sum_{n}a_{in}X_n$

**row operation** Left multiplication by an invertible matrix

**3 types of elementary nxn matrices**

1. One nonzero off-diagonal entry added to  the identity matrix

       Add a * (row j) to (row i) of X  
        
2. The ith and jth diagonal entries of the identity matrix replace by 0. 
Ones added in the (i, j) and (j, i) position

       Interchange (row i) and (row j) of X

3. One diagonal entry of the identity matrix is replaced by a nonzero scalar

       Multiply (row i) of X by nonzero scalar c
       
---

### Lemma 3

Elementary matrices are invertible, and their inverses are also elementary matrices.

---

### Row Reduction

$$
M' = E_{k} \cdots E_{1}M
$$

where $E_{n}$ are elementary operations. 

Can be used to solve system of equations using an augmented matrix.

M = [A|B] 

---

### Proposition 2

The systems A'X = B' and AX = B have the same solutions. 

##### Proof

M = [A|B]

Let $P = E_{k} \cdots E_{1}$ such that 

$$
M' = PM
$$

Then
$$
M' = [A'|B'] = [PA|PB]
$$

Given AX = B,
$$
PAX = PB
$$

$$
A'X = B'
$$

Thus X solves original equation. Similar logic if given $A'X=B'$ to start with.

---





# Exercises

##### 1. 

What are the entries of $a_{21}$ and $a_{23}$ of the matrix 
$
A=
\begin{bmatrix} 
1 & 2 & 5 \\
2 & 7 & 8 \\
0 & 9 & 4
\end{bmatrix}
$

Matrix entries are indexed by row first then column so $a_{21} = 2; a_{23} = 8$

---

##### 2. 

Determine the products AB and BA for the following values of A and B.


In [131]:
import numpy as np

def my_print(matrix, label=""):
    print(f"{label}\n{matrix}\n")

def show_products(array_A, array_B):
    A = np.array(array_A)
    B = np.array(array_B)

    my_print(A, "A")
    my_print(B, "B")
    my_print(np.matmul(A, B), "AB")
    my_print(np.matmul(B, A), "BA")
    print("========================")


A1 = [
    [1, 2, 3],
    [3, 3, 1]
] 

B1 = [
    [-8, -4],
    [9, 5],
    [-3, -2]
]

A2= [
    [1, 4],
    [1, 2]
]

B2 = [
    [6, -4],
    [3, 2]
]

show_products(A1, B1)
show_products(A2, B2)

A
[[1 2 3]
 [3 3 1]]

B
[[-8 -4]
 [ 9  5]
 [-3 -2]]

AB
[[1 0]
 [0 1]]

BA
[[-20 -28 -28]
 [ 24  33  32]
 [ -9 -12 -11]]

A
[[1 4]
 [1 2]]

B
[[ 6 -4]
 [ 3  2]]

AB
[[18  4]
 [12  0]]

BA
[[ 2 16]
 [ 5 16]]



---

##### 3. 

Let $A=[a_{1} \dots a_{n}]$ be a row vector, and let 

$B=
\begin{bmatrix}
    b_{1} \\ \vdots \\ b_{n} 
\end{bmatrix}$
be a column vector. Compute the products AB and BA.
 
$$
AB = \begin{bmatrix}\sum_{i=1}^{n}a_{i}b_{i}\end{bmatrix}
$$

Note that AB is a 1x1 matrix

$$
BA = 
\begin{bmatrix}
b_{1}a_{1} & \dots & b_{1}a_{n} \\
& \vdots \\
b_{n}a_{1} & \dots & b_{n}a_{n}
\end{bmatrix}
$$

---

##### 4. 

Verify the associative law for the below matrix products.

In [100]:
A = np.array([
    [1, 2],
    [0, 1]
])

B = np.array([
    [0, 1, 2],
    [1, 1, 3]
])

C = np.array([
    [1],
    [4],
    [3]
])

AB = np.matmul(A, B)
BC = np.matmul(B, C)

my_print(np.matmul(AB, C), "(AB)C")
my_print(np.matmul(A, BC), "A(BC)")
print("Does (AB)C = A(BC)?")
print(np.array_equal(np.matmul(AB, C), np.matmul(A, BC)))

(AB)C
[[38]
 [14]]

A(BC)
[[38]
 [14]]

Does (AB)C = A(BC)?
True


--- 

##### 5. 

Let A, B, C be matrices of sizes l x m, m x n, n x p. How many multiplications are required to compute the product AB? In which order should the triple product ABC be computed, so as to minimize the number of multiplications required?


- AB: Will result in a matrix with l x n entries. Each entry is a scalar product of two m-vectors which requires m multiplications (and m - 1 additions). So, AB requires **lmn** multiplications.

- ABC: 
    - (AB)C: (lmn) + (lnp) multiplications
    - A(BC): (mnp) + (lmp) multiplications

- The order to compute ABC should be chosen based on the whichever ever is smaller. 

--- 

##### 6.

Compute 

$$
\begin{bmatrix}
1 & a \\
  & 1
\end{bmatrix}
\begin{bmatrix}
1 & b \\
  & 1
\end{bmatrix}
$$

$$
\begin{bmatrix}
1 & a \\
  & 1
\end{bmatrix}^n
$$

Result

$$
\begin{bmatrix}
1 & a \\
  & 1
\end{bmatrix}
\begin{bmatrix}
1 & b \\
  & 1
\end{bmatrix} =
\begin{bmatrix}
1 & b + a \\
  & 1
\end{bmatrix}
$$

$$
\begin{bmatrix}
1 & a \\
  & 1
\end{bmatrix}^n
=
\begin{bmatrix}
1 & na \\
  & 1
\end{bmatrix}
$$

In [111]:
# Defined for exp >= 1
def matexp(matrix, exp):
    result = matrix
    for i in range(exp - 1):
        result = np.matmul(result, matrix)
    return result

matrix = np.array([
    [1, 7],
    [0, 1]
])

n = 4 
result = matexp(matrix, n)
my_print(result, f"n={n}")


n=4
[[ 1 28]
 [ 0  1]]



---

##### 7.

Find a formula for 
$
\begin{bmatrix}
    1 & 1 & 1 \\
      & 1 & 1 \\
      &   & 1
\end{bmatrix}^{n}
$, and prove it by induction.

Solution

$$
\begin{bmatrix}
    1 & 1 & 1 \\
      & 1 & 1 \\
      &   & 1
\end{bmatrix}^{n}
=
\begin{bmatrix}
    1 & n & \frac{n(n+1)}{2} \\
      & 1 & n \\
      &   & 1
\end{bmatrix}
$$

Proof

Clearly true for base case n = 1

Assume true for k. Show that k + 1 follows.

$$
\begin{bmatrix}
    1 & 1 & 1 \\
      & 1 & 1 \\
      &   & 1
\end{bmatrix}^{k+1}
=
\begin{bmatrix}
    1 & k & \frac{k(k+1)}{2} \\
      & 1 & k \\
      &   & 1
\end{bmatrix}
\begin{bmatrix}
    1 & 1 & 1 \\
      & 1 & 1 \\
      &   & 1
\end{bmatrix}
=
\begin{bmatrix}
    1 & k + 1 & \frac{(k+1)((k+1)+1)}{2} \\
      & 1 & k + 1\\
      &   & 1
\end{bmatrix}
$$



In [136]:
A = np.array([
    [1, 1, 1],
    [0, 1, 1],
    [0, 0, 1]
])

n = 7
result = matexp(A, n)

my_print(result, f"n={n}")

n=7
[[ 1  7 28]
 [ 0  1  7]
 [ 0  0  1]]



---

##### 8.

Compute the following products by block multiplication

$$
\begin{bmatrix}
1 & 1 | 1 & 5 \\
0 & 1 | 0 & 1 \\
\hline
1 & 0 | 0 & 1 \\
0 & 1 | 1 & 0
\end{bmatrix}
\begin{bmatrix}
1 & 2 | 1 & 0 \\
0 & 1 | 0 & 1 \\
\hline
1 & 0 | 0 & 1 \\
0 & 1 | 1 & 3
\end{bmatrix}
$$

In [156]:

A11 = np.array([
    [1, 1],
    [0, 1]
])

A12 = np.array([
    [1, 5],
    [0, 1]
])

A21 = np.array([
    [1, 0],
    [0, 1]
])

A22 = np.array([
    [0, 1],
    [1, 0]
])

B11 = np.array([
    [1, 2],
    [0, 1]
])

B12 = np.array([
    [1, 0],
    [0, 1]
])

B21 = np.array([
    [1, 0],
    [0, 1]
])

B22 = np.array([
    [0, 1],
    [1, 3]
])

A = np.block([
    [A11, A12],
    [A21, A22]        
])

B = np.block([
    [B11, B12],
    [B21, B22]        
]) 

block_multiplication = np.block([
    [np.matmul(A11, B11) + np.matmul(A12, B21), 
    np.matmul(A11, B12) + np.matmul(A12, B22)],
    [np.matmul(A21, B11) + np.matmul(A22,B12),
    np.matmul(A21, B12) + np.matmul(A22, B22)]
])

# Should be same
my_print(np.matmul(A,B), "Direct multiplication")
my_print(block_multiplication, "Block multiplication")


Direct multiplication
[[ 2  8  6 17]
 [ 0  2  1  4]
 [ 1  3  2  3]
 [ 1  1  0  2]]

Block multiplication
[[ 2  8  6 17]
 [ 0  2  1  4]
 [ 1  3  2  3]
 [ 1  1  0  2]]



---

##### 9.

Let A, B be square matrices,

- When is $(A+B)(A-B)=A^2-B^2$

Solution

$$
    (A+B)(A-B) = A^2 - AB - BA - B^2
$$

Clear that $(A+B)(A-B)=A^2-B^2$ if $AB=BA$

In words, when A and B *commute*

- Expand $(A+B)^3$

Solution

$$
(A+B)^3=(A+B)(A+B)(A+B)=
$$
$$
(A+B)(A^2+AB+BA+B^2)=
$$
$$
A^3+A^2B+ABA+AB^2+BA^2+BAB+B^2A+B^3
$$

---

##### 10.

Let D be the diagonal matrix with diagonal entries $d_{1} \dots d_{n}$ and let $A = (a_{ij})$ be an
arbitrary nXn matrix. Compute the products DA and AD.

Solution

$$
DA=
\begin{bmatrix}
    d_{1} & \dots & 0 \\
    & \vdots \\
    0 & \dots & d_{n}
\end{bmatrix}
\begin{bmatrix}
    a_{11} & \dots & a_{1n} \\
    & \vdots \\
    a_{n1} & \dots & a_{nn}
\end{bmatrix}=
\begin{bmatrix}
    d_{1}a_{11} & \dots & 0 \\
    & \vdots \\
    0 & \dots & d_{n}a_{nn}
\end{bmatrix}=
(d_{i}a_{ij})
$$

$$
AD=
\begin{bmatrix}
    a_{11} & \dots & a_{1n} \\
    & \vdots \\
    a_{n1} & \dots & a_{nn}
\end{bmatrix}
\begin{bmatrix}
    d_{1} & \dots & 0 \\
    & \vdots \\
    0 & \dots & d_{n}
\end{bmatrix}
=
\begin{bmatrix}
    d_{1}a_{11} & \dots & 0 \\
    & \vdots \\
    0 & \dots & d_{n}a_{nn}
\end{bmatrix}=
(d_{j}a_{ij})
$$

---

##### 11.

Prove that the product of upper triangular matrices is upper triangular.

Let A and B be upper triangular matrices.

$A = (a_{ij}) | a_{ij} = 0$ if $i > j$

$B = (b_{ij}) | b_{ij} = 0$ if $i > j$

$$
AB=(p_{ij})
$$
$$
p_{ij}=\sum_{v}a_{iv}b_{vj}
$$

Since A is triangular
$
p_{ij}=\sum_{v=i+1}a_{iv}b_{vj}
$

So
$
i > j \implies v > j \implies b_{vj} = 0  \implies p_{ij} = 0
$

Thus,

The product of upper triangular matrices is upper triangular.

---

##### 12

For each matrix, find all 2x2 matrices that commute with it.

- 
$$
\begin{bmatrix}
    1 & 0 \\
    0 & 0
\end{bmatrix}
$$

$$
\begin{bmatrix}
    1 & 0 \\
    0 & 0
\end{bmatrix}
\begin{bmatrix}
    a & b \\
    c & d
\end{bmatrix} =
\begin{bmatrix}
    a & b \\
    0 & 0
\end{bmatrix}
$$

$$
\begin{bmatrix}
    a & b \\
    c & d
\end{bmatrix}
\begin{bmatrix}
    1 & 0 \\
    0 & 0
\end{bmatrix} =
\begin{bmatrix}
    a & 0 \\
    c & 0
\end{bmatrix}
$$

$$
\begin{bmatrix}
    a & b \\
    0 & 0
\end{bmatrix}=
\begin{bmatrix}
    a & 0 \\
    c & 0
\end{bmatrix}
$$

Thus,
$
\begin{bmatrix}
a & 0 \\
0 & 0
\end{bmatrix}
$
and
$
\begin{bmatrix}
    1 & 0 \\
    0 & 0
\end{bmatrix}
$
commute

---

##### 13.

A square matrix A is **nilpotent** if $A^{k}$ = 0 for some k > 0. Prove that if A is nilpotent, then
I + A is invertible. Do this by finding the inverse.

Proof.

$$
I^{2k+1}+A^{2k+1} = (I + A)(I - A + A^{2} - \dots + (-1)^{2k}A^{2k})
$$

Since $I^n = I$ for any n, and $A^k = 0$

$$
I = (I + A)(I - A + A^{2} - \dots + (-1)^{k-1}A^{k-1})
$$

Thus,
$
(I - A + A^{2} - \dots + (-1)^{k-1}A^{k-1})
$ is the inverse of $(I + A)$ making it invertible.

---

##### 14.

With A arbitrary, determine the products $e_{ij}A, Ae{ij}, e_{j}Ae_{k}, e_{ii}Ae_{jj}, e_{ij}Ae_{kl}$

$$e_{ij}A = 
e_{ij} \sum_{km}a_{km}e_{km} =
\sum_{km}e_{ij} a_{km}e_{km} =
\sum_{km}a_{km}e_{ij} e_{km} =
$$

If $j \not= k$ then expression under sum results in zero.

$$
\sum_{m}a_{jm}e_{ij} e_{jm} = \sum_{m}a_{jm}e_{im}
$$



### 1.2.1

For the reduction of the matrix M (1.2.8) below, determine the elementary matrices corresponding to each operation. Compute the product P of these elementary matrices and verify that PM is indeed the end result.

![Figure 1.2.8](../../img/1-2-8.png)

In [33]:
import numpy as np

def multiply(*args):
    if len(args) < 2:
        print("Missing arguments")
        return
    
    result = args[0]
    for i in range(len(args) - 1):
        result = np.matmul(result, args[i+1])

    return result;

# Elementary Matrices

#  Add a*(row j) to (row i). 
def make_type1(n, i, j, a): 
    E = np.identity(n)
    E[i-1,j-1] = a
    return E

# Swap rows i and j.
def make_type2(n, i, j):
    E = np.identity(n)
    E[i-1,i-1] = 0
    E[j-1,j-1] = 0
    E[i-1, j-1] = 1
    E[j-1, i-1] = 1
    return E

# Multiply row i by nonzero scalar c.
def make_type3(n, i, c):
    E = np.identity(n)
    E[i-1,i-1] = c
    return E

M = np.reshape([
    1,1,2,1,5,
    1,1,2,6,10,
    1,2,5,2,7
], (3,5))

E1 = make_type1(3, 2, 1, -1)
E2 = make_type1(3, 3, 1,-1)
E3 = make_type2(3, 2, 3)
E4 = make_type1(3, 1, 2, -1)
E5 = make_type3(3, 3, .20)
E6 = make_type1(3, 2, 3, -1)

M_prime = multiply(E6, E5, E4, E3, E2, E1, M)
print(M_prime)




[[ 1.  0. -1.  0.  3.]
 [ 0.  1.  3.  0.  1.]
 [ 0.  0.  0.  1.  1.]]


In [177]:
import numpy as np
import sympy

smmpy.init_printing()

def solve(A, B):
    augmented = np.block([A, B])
    rref = sympy.Matrix(augmented).rref()

    rref_2d = np.reshape(rref[0], 
        (len(augmented), len(augmented[0])))

    pivot_indices = rref[1]
    num_pivots = len(pivot_indices)
    num_vars = len(A[0]) # is also the last column index
    
    # Pivot exists last column -> No solution
    if pivot_indices[-1] == num_vars:
        return None

    X = np.reshape([None] * num_vars, (num_vars, 1))

    for i in reversed(range(len(X))):
        if i + 1 > num_pivots:
            X[i] = sympy.Symbol(f"x_{i}")
        else:
            X[i] = rref_2d[i][num_vars]

            for j in range(num_vars):
                if i == j:
                    continue
                X[i] -= sympy.Symbol(f"x_{i}") * rref_2d[i][j]
    return X
   

A = np.reshape([
    1,2,1,1,
    3,0,0,4,
    1,-4,-2,2
], (3,4))

B1 = np.reshape([
    0,
    0,
    0
],(3,1))

B2 = np.reshape([
    1,
    1,
    0
],(3,1))

B3 = np.reshape([
    0,
    2,
    2
],(3,1))

for B in [B1, B2, B3]:
    result = solve(A, B)
    result
    print()
