# Matrices

---

### Definitions

$$
M = \begin{bmatrix}
       a_{11} & \dots & a_{1n}          \\
       \vdots &            & \vdots      \\
       a_{m1}         & \dots & a_{mn}
     \end{bmatrix}
$$

The matrix entries are denoted as
$a_{ij}$ where
*i* is the row index and
*j* is the col index.

$(a_{ij})$ denotes the matrix whose entries are $a_{ij}$. Avoid this notation where it risks causing confusion with perhaps more familiar parenthesis usage (order of operation).

**Square matrix**: *n* x *n*

**Row vector**: 1 x *n*

**Column vector**: *n* x 1

---

### Addition

Defined when both matrices have same dimensions.

($s_{ij}$) = ($a_{ij}$) + ($b_{ij}$) 

where

$s_{ij}$ = $a_{ij}$ + $b_{ij}$ 

### Scalar Multiplication

*c* ($a_{ij}$) = ($c a_{ij}$)

### Matrix Multiplication

Defined for matrices A and B where the number of columns in A equals the number of rows of B.


$$
(p_{ij}) = AB
$$

$$
p_{ij} = \sum_{v}a_{iv}b_{vj}
$$

Provides another way to write a system of equations.

$$
a_{11}x_{1} + \dots + a_{1n}x_{n} = b_{1} \\
\vdots                                    \\
a_{m1}x_{1} + \dots + a_{mn}x_{n} = b_{n}
$$

can be expressed as $AX = B$, 
where A is the matrix of coefficients, 
X and B are columns vectors.

---

### Distributive Law

$$
L(A + B) = LA + LB
$$ 
$$
(A + B)R = AR + BR
$$

### Associative Law

$$
(AB)C = A(BC)
$$

### NOT Commutative 

Occasionally can be, but in general **cannot** assume that $AB = BA$

---

### More Definitions

**zero matrix**: All entries are 0. Denoted as just 0 if no confusion.

**diagonal entries**: $a_{ii}$

**diagonal matrix**: Only nonzero entries are diagonal entries

**identity matrix**: The *n* x *n* diagonal matrix whose diagonal entries all equal 1. Denoted $I_{n}$ 

If A is *m* x *n* matrix then

$$
AI_{n} = A 
$$
$$
I_{m}A = A
$$

**inverse matrix**: Denoted by $A^{-1}$

$$
A^{-1}A = I = AA^{-1}
$$

**invertible**: If an inverse exists

---

### Lemma 1

Let A be a square matrix that has a right inverse, a matrix R such that AR = I
and also a left inverse, a matrix L such that LA = I. Then R = L. So A is invertible and R is its inverse.

##### Proof

$$
R = IR = (LA)R = L(AR) = LI = L
$$

---

### Proposition 1
If $A$ and $B$ are invertible,
Then
- $AB$ is invertible
- $A^{-1}$ is invertible
- $(AB)^{-1} = B^{-1}A^{-1}$ (Generalized below)

If $A_{1}, \dots\, A_{m}$ are invertible,
Then

$$
(A_{1} \cdots\ A_{m})^{-1} = A_{m}^{-1} \cdots A_{1}^{-1}
$$

##### Proof

By definition

$$
(A_{1} \cdots\ A_{m})^{-1}(A_{1} \cdots\ A_{m}) = I = (A_{1} \cdots\ A_{m})(A_{1} \cdots\ A_{m})^{-1}
$$

Consider

$$
(A_{1} \cdots\ A_{m})           (A_{m}^{-1} \cdots\ A_{1}^{-1}) =
$$
$$
(A_{1} \cdots\ A_{m-1})  (A_{m}A_{m}^{-1})        (A_{m-1}^{-1} \cdots\ A_{1}^{-1}) =
$$
$$
(A_{1} \cdots\ A_{m-1})     I   (A_{m-1}^{-1} \cdots\ A_{1}^{-1}) =
$$
$$
(A_{1} \cdots\ A_{m-1})(A_{m-1}^{-1} \cdots\ A_{1}^{-1}) =
$$
$$
\dots = A_{1}A_{1}^{-1} = I
$$

Similar logic shows that 

$$
(A_{m}^{-1} \cdots\ A_{1}^{-1})(A_{1} \cdots\ A_{m}) = I
$$

Thus

$$
(A_{1} \cdots\ A_{m})^{-1} = A_{m}^{-1} \cdots\ A_{1}^{-1}
$$

---

### Determinant 

$ad-bc$ is the determinant of a 2x2 matrix. If the determinant is 0 then the matrix is not invertible

$$
\begin{bmatrix}
      a & b \\
      c & d
\end{bmatrix}^{-1} = 
\frac{1}{ad-bc}
\begin{bmatrix}
      d & -b \\
      -c & a
\end{bmatrix}
$$

***n*-dimensional general linear group**: Set of all invertible nxn matrices.

---

### Lemma 2 
A square matrix that has either a row or column of 0s is not invertible.

##### Proof

Given n x n matrices A and B.

If matrix A has row of 0s then the corresponding row in AB also has all 0s.

So at least one diagonal entry of AB is not one.

So $AB \not= I_{n}$

So A has no right inverse.

If matrix A has a column of 0s then the corresponding column in BA also has all 0s.

So at least one diagonal entry of BA is not one.

So $BA \not= I_{n}$

So A has no left inverse.

Thus, A is not invertible. 

---

### Block Multiplication





---

# Code

Examples of how to work with matrices using python.

### Basics

In [59]:
import numpy as np

def my_print(matrix, label=""):
    print(f"{label}\n{matrix}\n")

A = np.array([[1, 2], [4, 5]])
B = np.array([[2, 3], [5, 6]])

# Can also use complex numbers
C = np.array([1, 5 + 3j])

# dtype defaults to floating
zeros = np.zeros( (2, 2), dtype=np.int32 )
identity = np.diag(np.ones(2, dtype=np.int32))

my_print(A, "A")
my_print(B, "B")
my_print(C, "C")
my_print(zeros, "0")
my_print(identity, "I")
my_print(A + zeros, "A + 0")
my_print(A + B, "A + B")
my_print(np.matmul(A,B), "AB")





A
[[1 2]
 [4 5]]

B
[[2 3]
 [5 6]]

C
[1.+0.j 5.+3.j]

0
[[0 0]
 [0 0]]

I
[[1 0]
 [0 1]]

A + 0
[[1 2]
 [4 5]]

A + B
[[ 3  5]
 [ 9 11]]

AB
[[12 15]
 [33 42]]



In [64]:
a = np.array([[0, 0], [1, 2]])
b = np.array([[1, 2], [3, 4]])

c = np.matmul(a, b)
print(c)


[[ 0  0]
 [ 7 10]]
